create sequence SEQ_LAU_CRON start with 1 increment by 1;
create sequence SEQ_LAU_INBOX start with 1 increment by 1;
create sequence SEQ_LAU_INBOX_EVENT start with 1 increment by 1;
create sequence SEQ_LAU_INBOX_PAYLOAD start with 1 increment by 1;
create sequence SEQ_LAU_INBOX_PAYLOAD_PROP start with 1 increment by 1;
create sequence SEQ_LAU_INBOX_PROP start with 1 increment by 1;
create sequence SEQ_LAU_INTERC_INST_PROP start with 1 increment by 1;
create sequence SEQ_LAU_INTERC_RULE start with 1 increment by 1;
create sequence SEQ_LAU_INTERCEPTOR start with 1 increment by 1;
create sequence SEQ_LAU_OUTBOX start with 1 increment by 1;
create sequence SEQ_LAU_OUTBOX_EVENT start with 1 increment by 1;
create sequence SEQ_LAU_OUTBOX_PAYLOAD start with 1 increment by 1;
create sequence SEQ_LAU_OUTBOX_PAYLOAD_PROP start with 1 increment by 1;
create sequence SEQ_LAU_OUTBOX_PROP start with 1 increment by 1;
create sequence SEQ_LAU_PROC_INST_PROP start with 1 increment by 1;
create sequence SEQ_LAU_PROCESS_INSTANCE start with 1 increment by 1;
create sequence SEQ_LAU_PROCESSOR start with 1 increment by 1;
create sequence SEQ_LAU_PROCESSOR_RULE start with 1 increment by 1;
create sequence SEQ_LAU_TASK_INSTANCE start with 1 increment by 1;
create sequence SEQ_LAU_TASK_PROP start with 1 increment by 1;
create table LAU_APPLICATION (application_Id VARCHAR(512) not null, NAME VARCHAR(512), DESCRIPTION VARCHAR(1024), EMAIL VARCHAR(512), Active_Date_From timestamp, Active_Date_To timestamp, primary key (application_Id));
create table lau_application_sedbox (applicationId VARCHAR(512) not null, lau_box VARCHAR(512) not null);
create table LAU_BOX (LOCAL_BOX_NAME VARCHAR(512) not null, Active_Date_From timestamp, Active_Date_To timestamp, primary key (LOCAL_BOX_NAME));
create table LAU_CERT_PASSWD (ALIAS VARCHAR(64) not null, PASSWORD VARCHAR(64), KEY_PASSWORD SMALLINT, primary key (ALIAS));
create table LAU_CRON (ID DECIMAL(19) not null, NAME VARCHAR(128), ACTIVE SMALLINT, CRON_SECOND VARCHAR(64), CRON_MINUTE VARCHAR(64), CRON_HOUR VARCHAR(64), CRON_DAY_OF_MONTH VARCHAR(64), CRON_MONTH VARCHAR(64), CRON_DAY_OF_WEEK VARCHAR(64), CRON_IGNORE_ON_WORK_FREE_DAYS SMALLINT, primary key (ID));
create table LAU_INBOX (ID DECIMAL(19) not null, MSG_ID VARCHAR(256) not null, REF_TO_MSG_ID VARCHAR(256), SENDER_MSG_ID VARCHAR(256), SERVICE VARCHAR(512) not null, ACTION VARCHAR(512) not null, CONV_Id VARCHAR(512), SUBJECT VARCHAR(512), RECEIVER_EBOX VARCHAR(512) not null, RECEIVER_NAME VARCHAR(512), SENDER_EBOX VARCHAR(512) not null, SENDER_NAME VARCHAR(512), STATUS VARCHAR(32), DATE_STATUS timestamp, DATE_SUBMITTED timestamp, DATE_SENT timestamp, DATE_RECEIVED timestamp, DATE_DELIVERED timestamp, primary key (ID));
create table LAU_INBOX_EVENT (ID DECIMAL(19) not null, MAIL_ID DECIMAL(19), STATUS VARCHAR(32), EVENT_DATE timestamp, DESCRIPTION VARCHAR(512), USER_ID VARCHAR(64), APPLICATION_ID VARCHAR(128), FILEPATH VARCHAR(1028), MIME_TYPE VARCHAR(128), primary key (ID));
create table LAU_INBOX_PAYLOAD (ID DECIMAL(19) not null, MAIL_ID DECIMAL(19), PART_EBMS_ID VARCHAR(256), PART_NAME VARCHAR(256), PART_DESCRIPTION VARCHAR(512), PART_TYPE VARCHAR(64), PART_FILENAME VARCHAR(256), PART_FILEPATH VARCHAR(1028), PART_MIME_TYPE VARCHAR(128), PART_ENCODING VARCHAR(128), PART_SHA256_VALUE VARCHAR(256), PART_SIZE DECIMAL(19), PART_IS_ENCRYPTED SMALLINT, PART_SOURCE VARCHAR(32), PART_IS_RECEIVED SMALLINT, PART_IS_SENT SMALLINT, PART_GENERATED_FROM_PART DECIMAL(19), primary key (ID));
create table LAU_INBOX_PAYLOAD_PROPERTY (ID DECIMAL(19) not null, NAME VARCHAR(128), TYPE VARCHAR(256), VALUE VARCHAR(512), INPART_ID DECIMAL(19) not null, primary key (ID));
create table LAU_INBOX_PROPERTY (ID DECIMAL(19) not null, NAME VARCHAR(128), TYPE VARCHAR(256), VALUE VARCHAR(512), MAIL_ID DECIMAL(19) not null, primary key (ID));
create table LAU_INTERC_INST_PROPERTY (ID DECIMAL(19) not null, INTC_PROP_KEY VARCHAR(64), INTC_PROP_VALUE VARCHAR(512), INTERCEPTOR_INSTANCE_ID DECIMAL(19) not null, primary key (ID));
create table LAU_INTERC_RULE (ID DECIMAL(19) not null, RULE_PROPERTY VARCHAR(64), RULE_PREDICATE VARCHAR(32), RULE_VALUE VARCHAR(512), INTERCEPTOR_ID DECIMAL(19) not null, primary key (ID));
create table LAU_INTERCEPTOR (ID DECIMAL(19) not null, NAME VARCHAR(128), ACTIVE SMALLINT, INTERCEPT_EVENT VARCHAR(32), INTERCEPT_ROLE VARCHAR(32), INTERCEPTOR_TYPE VARCHAR(64), INTERCEPTOR_PLUGIN VARCHAR(64), INTERCEPTOR_PLUGIN_VERSION VARCHAR(32), primary key (ID));
create table LAU_OUTBOX (ID DECIMAL(19) not null, MSG_ID VARCHAR(256) not null, REF_TO_MSG_ID VARCHAR(256), SENDER_MSG_ID VARCHAR(256), SERVICE VARCHAR(512) not null, ACTION VARCHAR(512) not null, CONV_ID VARCHAR(512), SUBJECT VARCHAR(512), RECEIVER_EBOX VARCHAR(512) not null, RECEIVER_NAME VARCHAR(512), SENDER_EBOX VARCHAR(512) not null, SENDER_NAME VARCHAR(512), STATUS VARCHAR(32), DATE_STATUS timestamp, DATE_SUBMITTED timestamp, DATE_SENT timestamp, DATE_RECEIVED timestamp, DATE_DELIVERED timestamp, primary key (ID));
create table LAU_OUTBOX_EVENT (ID DECIMAL(19) not null, MAIL_ID DECIMAL(19), SENDER_MSG_ID VARCHAR(256), STATUS VARCHAR(32), EVENT_DATE timestamp, DESCRIPTION VARCHAR(512), USER_ID VARCHAR(64), APPLICATION_ID VARCHAR(128), FILEPATH VARCHAR(1028), MIME_TYPE VARCHAR(128), primary key (ID));
create table LAU_OUTBOX_PAYLOAD (ID DECIMAL(19) not null, MAIL_ID DECIMAL(19), PART_EBMS_ID VARCHAR(256), PART_NAME VARCHAR(256), PART_DESCRIPTION VARCHAR(512), PART_TYPE VARCHAR(64), PART_FILENAME VARCHAR(256), PART_FILEPATH VARCHAR(1028), PART_MIME_TYPE VARCHAR(128), PART_ENCODING VARCHAR(128), PART_SHA256_VALUE VARCHAR(256), PART_SIZE DECIMAL(19), PART_IS_ENCRYPTED SMALLINT, PART_SOURCE VARCHAR(32), PART_IS_RECEIVED SMALLINT, PART_IS_SENT SMALLINT, PART_GENERATED_FROM_PART DECIMAL(19), primary key (ID));
create table LAU_OUTBOX_PAYLOAD_PROPERTY (ID DECIMAL(19) not null, NAME VARCHAR(128), TYPE VARCHAR(256), VALUE VARCHAR(512), OUTPART_ID DECIMAL(19) not null, primary key (ID));
create table LAU_OUTBOX_PROPERTY (ID DECIMAL(19) not null, NAME VARCHAR(128), TYPE VARCHAR(256), VALUE VARCHAR(512), MAIL_ID DECIMAL(19) not null, primary key (ID));
create table LAU_PROC_INST_PROPERTY (ID DECIMAL(19) not null, PROC_PROP_KEY VARCHAR(64), PROC_PROP_VALUE VARCHAR(512), PROCESSOR_INSTANCE_ID DECIMAL(19) not null, primary key (ID));
create table LAU_PROCESS_INSTANCE (ID DECIMAL(19) not null, TYPE VARCHAR(64), PLUGIN VARCHAR(64), PLUGIN_VERSION VARCHAR(32), PROCESSOR_ID DECIMAL(19,2), IDX BIGINT, primary key (ID));
create table LAU_PROCESSOR (ID DECIMAL(19) not null, NAME VARCHAR(128), ACTIVE SMALLINT, SET_DELIVERED_ON_SUCCESS SMALLINT, primary key (ID));
create table LAU_PROCESSOR_RULE (ID DECIMAL(19) not null, RULE_PROPERTY VARCHAR(64), RULE_PREDICATE VARCHAR(32), RULE_VALUE VARCHAR(512), PROCESSOR_ID DECIMAL(19) not null, primary key (ID));
create table LAU_SETTINGS (PROP_KEY VARCHAR(512) not null, PROP_VALUE VARCHAR(1024), LAU_GROUP VARCHAR(32), primary key (PROP_KEY));
create table LAU_TASK_INSTANCE (TASK_ID DECIMAL(19) not null, TASK_TYPE VARCHAR(64), TASK_PLUGIN VARCHAR(64), TASK_PLUGIN_VERSION VARCHAR(32), TASK_NAME VARCHAR(128), TASK_ACTIVE SMALLINT, CRON_ID DECIMAL(19,2), IDX BIGINT, primary key (TASK_ID));
create table LAU_TASK_PROPERTY (ID DECIMAL(19) not null, TASK_PROP_KEY VARCHAR(64), TASK_PROP_VALUE VARCHAR(512), TASK_ID DECIMAL(19) not null, primary key (ID));
create table LAU_USER (userid VARCHAR(512) not null, NAME VARCHAR(512), DESCRIPTION VARCHAR(1024), EMAIL VARCHAR(512), Active_Date_From timestamp, Active_Date_To timestamp, primary key (userid));
create table lau_user_sedbox (userid VARCHAR(512) not null, lau_box VARCHAR(512) not null);
create table Status (ID VARCHAR(255) not null, SERVICE VARCHAR(255), STATUS VARCHAR(255), COUNT DECIMAL(19,2), primary key (ID));
alter table LAU_CRON add constraint UK_p4lugycxfd6vfse3wtg92vok0 unique (NAME);
create index Idx_in_msg_id on LAU_INBOX (MSG_ID);
create index idx_in_ref_msg_id on LAU_INBOX (REF_TO_MSG_ID);
create index Idx_sender_msg_id on LAU_INBOX (SENDER_MSG_ID);
create index Idx_conv_id on LAU_INBOX (CONV_Id);
create index Idx_status on LAU_INBOX (STATUS);
create index Idx_date_status on LAU_INBOX (DATE_STATUS);
create index Idx_date_submit on LAU_INBOX (DATE_SUBMITTED);
create index Idx_date_sent on LAU_INBOX (DATE_SENT);
create index Idx_date_received on LAU_INBOX (DATE_RECEIVED);
create index Idx_date_delivered on LAU_INBOX (DATE_DELIVERED);
create index idx_inev_mid on LAU_INBOX_EVENT (MAIL_ID);
create index idx_inpart_mid on LAU_INBOX_PAYLOAD (MAIL_ID);
create index idx_inpart_ebmsid on LAU_INBOX_PAYLOAD (PART_EBMS_ID);
alter table LAU_INTERCEPTOR add constraint UK_2yn4pf1e0fcqtx9wimeve8ng2 unique (NAME);
create index idx_out_msg_id on LAU_OUTBOX (MSG_ID);
create index idx_out_ref_msg_id on LAU_OUTBOX (REF_TO_MSG_ID);
create index idx_out_sender_msg_id on LAU_OUTBOX (SENDER_MSG_ID);
create index idx_out_conv_id on LAU_OUTBOX (CONV_ID);
create index idx_out_status on LAU_OUTBOX (STATUS);
create index idx_out_date_status on LAU_OUTBOX (DATE_STATUS);
create index idx_out_date_submit on LAU_OUTBOX (DATE_SUBMITTED);
create index idx_out_date_sent on LAU_OUTBOX (DATE_SENT);
create index idx_out_date_received on LAU_OUTBOX (DATE_RECEIVED);
create index idx_out_date_delivered on LAU_OUTBOX (DATE_DELIVERED);
create index idx_outev_mid on LAU_OUTBOX_EVENT (MAIL_ID);
create index idx_oute_smid on LAU_OUTBOX_EVENT (SENDER_MSG_ID);
create index idx_outpart_mid on LAU_OUTBOX_PAYLOAD (MAIL_ID);
create index idx_outpart_ebmsid on LAU_OUTBOX_PAYLOAD (PART_EBMS_ID);
create index Idx_proc_name on LAU_PROCESSOR (NAME);
alter table LAU_PROCESSOR add constraint UK_q3kusunk2g5xmrl2bpv2qp86w unique (NAME);
alter table lau_application_sedbox add constraint FKfh4o2fkuupgbg3fbs01oqok98 foreign key (lau_box) references LAU_BOX;
alter table lau_application_sedbox add constraint FKo0vipa03a8x1qeen7v59jnj5g foreign key (applicationId) references LAU_APPLICATION;
alter table LAU_INBOX_PAYLOAD add constraint FKhfeuj7x6gu79rwjb51yjgm6na foreign key (MAIL_ID) references LAU_INBOX;
alter table LAU_INBOX_PAYLOAD_PROPERTY add constraint FKcffyndj75961psteakf0bgcpv foreign key (INPART_ID) references LAU_INBOX_PAYLOAD;
alter table LAU_INBOX_PROPERTY add constraint FKoxlhcbysl1wyb8y61s7ji6rix foreign key (MAIL_ID) references LAU_INBOX;
alter table LAU_INTERC_INST_PROPERTY add constraint FK25lg28ch3j0sm93otq1t3i0qq foreign key (INTERCEPTOR_INSTANCE_ID) references LAU_INTERCEPTOR;
alter table LAU_INTERC_RULE add constraint FKry3q0vilbnmnjn3si8praj09u foreign key (INTERCEPTOR_ID) references LAU_INTERCEPTOR;
alter table LAU_OUTBOX_PAYLOAD add constraint FKdnhy6eicnlt3x90tbm0s8hl4i foreign key (MAIL_ID) references LAU_OUTBOX;
alter table LAU_OUTBOX_PAYLOAD_PROPERTY add constraint FK4br36icwb4ykah4c1dn96e7x foreign key (OUTPART_ID) references LAU_OUTBOX_PAYLOAD;
alter table LAU_OUTBOX_PROPERTY add constraint FKjuvytr3148ok3wkgnafbx86uc foreign key (MAIL_ID) references LAU_OUTBOX;
alter table LAU_PROC_INST_PROPERTY add constraint FKswnd8ofr9a9i914a3jnsowcj2 foreign key (PROCESSOR_INSTANCE_ID) references LAU_PROCESS_INSTANCE;
alter table LAU_PROCESS_INSTANCE add constraint FKh8rl7cuwpmwlykan7c9k1qsal foreign key (PROCESSOR_ID) references LAU_PROCESSOR;
alter table LAU_PROCESSOR_RULE add constraint FKnqhnt0ifieah239jvl4j89efr foreign key (PROCESSOR_ID) references LAU_PROCESSOR;
alter table LAU_TASK_INSTANCE add constraint FK3dq8n8wou6jjjra0hksqi74ni foreign key (CRON_ID) references LAU_CRON;
alter table LAU_TASK_PROPERTY add constraint FK6yaein29p27bgvlvu7uj7tytk foreign key (TASK_ID) references LAU_TASK_INSTANCE;
alter table lau_user_sedbox add constraint FKskjfj7e21bd85ms4680q9t72n foreign key (lau_box) references LAU_BOX;
alter table lau_user_sedbox add constraint FKedyfksnua3b07c0jt0cpj4l3c foreign key (userid) references LAU_USER;
