drop table LAU_APPLICATION cascade;
drop table lau_application_sedbox cascade;
drop table LAU_BOX cascade;
drop table LAU_CERT_PASSWD cascade;
drop table LAU_CRON cascade;
drop table LAU_INBOX cascade;
drop table LAU_INBOX_EVENT cascade;
drop table LAU_INBOX_PAYLOAD cascade;
drop table LAU_INBOX_PAYLOAD_PROPERTY cascade;
drop table LAU_INBOX_PROPERTY cascade;
drop table LAU_INTERC_INST_PROPERTY cascade;
drop table LAU_INTERC_RULE cascade;
drop table LAU_INTERCEPTOR cascade;
drop table LAU_OUTBOX cascade;
drop table LAU_OUTBOX_EVENT cascade;
drop table LAU_OUTBOX_PAYLOAD cascade;
drop table LAU_OUTBOX_PAYLOAD_PROPERTY cascade;
drop table LAU_OUTBOX_PROPERTY cascade;
drop table LAU_PROC_INST_PROPERTY cascade;
drop table LAU_PROCESS_INSTANCE cascade;
drop table LAU_PROCESSOR cascade;
drop table LAU_PROCESSOR_RULE cascade;
drop table LAU_SETTINGS cascade;
drop table LAU_TASK_INSTANCE cascade;
drop table LAU_TASK_PROPERTY cascade;
drop table LAU_USER cascade;
drop table lau_user_sedbox cascade;
drop table Status cascade;
drop sequence SEQ_LAU_CRON;
drop sequence SEQ_LAU_INBOX;
drop sequence SEQ_LAU_INBOX_EVENT;
drop sequence SEQ_LAU_INBOX_PAYLOAD;
drop sequence SEQ_LAU_INBOX_PAYLOAD_PROP;
drop sequence SEQ_LAU_INBOX_PROP;
drop sequence SEQ_LAU_INTERC_INST_PROP;
drop sequence SEQ_LAU_INTERC_RULE;
drop sequence SEQ_LAU_INTERCEPTOR;
drop sequence SEQ_LAU_OUTBOX;
drop sequence SEQ_LAU_OUTBOX_EVENT;
drop sequence SEQ_LAU_OUTBOX_PAYLOAD;
drop sequence SEQ_LAU_OUTBOX_PAYLOAD_PROP;
drop sequence SEQ_LAU_OUTBOX_PROP;
drop sequence SEQ_LAU_PROC_INST_PROP;
drop sequence SEQ_LAU_PROCESS_INSTANCE;
drop sequence SEQ_LAU_PROCESSOR;
drop sequence SEQ_LAU_PROCESSOR_RULE;
drop sequence SEQ_LAU_TASK_INSTANCE;
drop sequence SEQ_LAU_TASK_PROP;
