
package si.laurentius;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "mailbox", targetNamespace = "http://si.laurentius", wsdlLocation = "file:/sluzba/code/SVEV2.0/Laurentius/Laurentius-libs/Laurentius-wsdl/src/main/resources/wsdl/mailbox.wsdl")
public class SedMailbox
    extends Service
{

    private final static URL SEDMAILBOX_WSDL_LOCATION;
    private final static WebServiceException SEDMAILBOX_EXCEPTION;
    private final static QName SEDMAILBOX_QNAME = new QName("http://si.laurentius", "mailbox");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/sluzba/code/SVEV2.0/Laurentius/Laurentius-libs/Laurentius-wsdl/src/main/resources/wsdl/mailbox.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEDMAILBOX_WSDL_LOCATION = url;
        SEDMAILBOX_EXCEPTION = e;
    }

    public SedMailbox() {
        super(__getWsdlLocation(), SEDMAILBOX_QNAME);
    }

    public SedMailbox(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEDMAILBOX_QNAME, features);
    }

    public SedMailbox(URL wsdlLocation) {
        super(wsdlLocation, SEDMAILBOX_QNAME);
    }

    public SedMailbox(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEDMAILBOX_QNAME, features);
    }

    public SedMailbox(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SedMailbox(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SEDMailBoxWS
     */
    @WebEndpoint(name = "SEDMailBoxWSPort")
    public SEDMailBoxWS getSEDMailBoxWSPort() {
        return super.getPort(new QName("http://si.laurentius", "SEDMailBoxWSPort"), SEDMailBoxWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEDMailBoxWS
     */
    @WebEndpoint(name = "SEDMailBoxWSPort")
    public SEDMailBoxWS getSEDMailBoxWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://si.laurentius", "SEDMailBoxWSPort"), SEDMailBoxWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEDMAILBOX_EXCEPTION!= null) {
            throw SEDMAILBOX_EXCEPTION;
        }
        return SEDMAILBOX_WSDL_LOCATION;
    }

}
