<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by XMLSpy 2007 Professional Ed., Installed for 5 users (with SMP from 2007-02-06 to 2008-02-07) (CIF VSRS) -->
<xs:schema xmlns:tns="ws.dc.cif.vsrs.si" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ud="ws.dc.cif.vsrs.si/UserData" xmlns:scr="ws.dc.cif.vsrs.si/SCRControl" targetNamespace="ws.dc.cif.vsrs.si">
	<xs:import namespace="ws.dc.cif.vsrs.si/SCRControl" schemaLocation="../XmlCommon/SCRControl.xsd"/>
	<xs:element name="SCDCInputModuleAddDCInputEntryResponse">
		<xs:annotation>
			<xs:documentation>Service parameters and results</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SCRControl" type="scr:SCRControl"/>
				<xs:element name="RData">
					<xs:complexType>
						<xs:attribute name="id" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
