<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tns="ws.dc.cif.vsrs.si" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:scc="ws.dc.cif.vsrs.si/SCControl" targetNamespace="ws.dc.cif.vsrs.si">
	<xs:import namespace="ws.dc.cif.vsrs.si/SCControl" schemaLocation="../XmlCommon/SCControl.xsd"/>
	<xs:element name="SCDespatchCentreGetCompletedPDIdsRequest">
		<xs:annotation>
			<xs:documentation>Metoda je prototip in se ni implemetnirana</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SCControl" type="scc:SCControl"/>
				<xs:element name="Data">
					<xs:complexType>
						<xs:attribute name="dateFrom" type="xs:date" use="required">
							<xs:annotation>
								<xs:documentation>Zacetni cas poizvedbe</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="dateTo" type="xs:date" use="required">
							<xs:annotation>
								<xs:documentation>Koncni cas poizvedbe</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="aplikSif" use="required">
							<xs:annotation>
								<xs:documentation>Sifra aplikacije</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:length value="70"/>
				</xs:restriction>
			</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="sodiSif" >
							<xs:annotation>
								<xs:documentation>Sifra sodisca</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:length value="3"/>
				</xs:restriction>
			</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
