<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tns="ws.dc.cif.vsrs.si" 
           targetNamespace="ws.dc.cif.vsrs.si" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:scc="ws.dc.cif.vsrs.si/SCControl"
           xmlns:dc="ws.dc.cif.vsrs.si/DespatchCentre"  >
    <xs:import namespace ="ws.dc.cif.vsrs.si/SCControl" schemaLocation="../XmlCommon/SCControl.xsd"/>
    <xs:import  namespace ="ws.dc.cif.vsrs.si/DespatchCentre" schemaLocation="DespatchCentre.xsd"/>
    <xs:element name="SCDespatchCentreAddDespatchCentreRequest" >
        <xs:annotation>
            <xs:documentation>Service parameters and results</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SCControl" type="scc:SCControl" minOccurs="0"/>
                <xs:element name="Data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DespatchCentre" type="dc:DespatchCentre"  />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
