<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tns="ws.dc.cif.vsrs.si" 
            targetNamespace="ws.dc.cif.vsrs.si" 
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:scc="ws.dc.cif.vsrs.si/SCControl" >
    <xs:import namespace ="ws.dc.cif.vsrs.si/SCControl" schemaLocation="../XmlCommon/SCControl.xsd"/>
    <xs:element name="SCDespatchCentreGetCurrentDCEntryStatusRequest" >
        <xs:annotation>
            <xs:documentation>Service parameters and results</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SCControl" type="scc:SCControl" />
                <xs:element name="Data">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:int"  />
                        <xs:attribute name="aplikRefIdZadeva" type="xs:token"  />
                        <xs:attribute name="aplikRefPosiljke" type="xs:token"  />
                        <xs:attribute name="rStev" type="xs:int" />
                        <xs:attribute name="aplikSif" type="xs:token"/>
                        <xs:attribute name="sodiSif" type="xs:token"/>
                        <xs:attribute name="vpisnikSif" type="xs:token"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
