
package laurentius.si;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SEDException", targetNamespace = "http://si.laurentius")
public class SEDException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SEDException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SEDException_Exception(String message, SEDException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SEDException_Exception(String message, SEDException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: laurentius.si.SEDException
     */
    public SEDException getFaultInfo() {
        return faultInfo;
    }

}
