/*
* Copyright 2016, Supreme Court Republic of Slovenia 
*
* Licensed under the EUPL, Version 1.1 or – as soon they will be approved by 
* the European Commission - subsequent versions of the EUPL (the "Licence");
* You may not use this work except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/software/page/eupl
*
* Unless required by applicable law or agreed to in writing, software 
* distributed under the Licence is distributed on an "AS IS" basis, WITHOUT 
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and  
* limitations under the Licence.
 */
package si.jrc.msh.plugin.meps.utils;

/**
 *
 * @author Jože Rihtaršič
 */
public class TCLookUp {
  public static String[][] TEST_COURT_ADDRESSES = new String[][]{
  {"Delovno in socialno sodišče v Ljubljani", "Delovni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Delovno in socialno sodišče v Ljubljani", "Izvršilni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Delovno in socialno sodišče v Ljubljani", "Urad sodišča", "Resljeva 14", "1000", "Ljubljana"},
{"Delovno in socialno sodišče v Ljubljani - Oddelek v Brežicah", "Delovni oddelek", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Delovno in socialno sodišče v Ljubljani - Oddelek v Brežicah", "Izvršilni oddelek", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Delovno in socialno sodišče v Ljubljani - Oddelek v Kranju", "Delovni oddelek", "Nazorjeva 1", "4000", "Kranj"},
{"Delovno in socialno sodišče v Ljubljani - Oddelek v Kranju", "Izvršilni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Delovno in socialno sodišče v Ljubljani - Oddelek v Novem mestu", "Delovni oddelek", "Vrhovčeva 18/I", "8000", "Novo mesto"},
{"Delovno in socialno sodišče v Ljubljani - Oddelek v Novem mestu", "Izvršilni oddelek", "Vrhovčeva 16", "8000", "Novo mesto"},
{"Delovno in socialno sodišče v Ljubljani - Socialno sodišče", "Izvršilni oddelek", "Komenskega 7", "1000", "Ljubljana"},
{"Delovno in socialno sodišče v Ljubljani - Socialno sodišče", "Pravdni oddelek", "Komenskega 7", "1000", "Ljubljana"},
{"Delovno in socialno sodišče v Ljubljani - Socialno sodišče", "Socialni oddelek", "Komenskega 7", "1000", "Ljubljana"},
{"Delovno in socialno sodišče v Ljubljani - Socialno sodišče", "Urad sodišča", "Komenskega 7", "1000", "Ljubljana"},
{"Delovno sodišče v Celju", "Delovni oddelek", "Gregorčičeva 6", "3000", "Celje"},
{"Delovno sodišče v Celju", "Izvršilni oddelek", "Gregorčičeva 6", "3000", "Celje"},
{"Delovno sodišče v Celju", "Urad sodišča", "Gregorčičeva 6", "3000", "Celje"},
{"Delovno sodišče v Kopru", "Delovni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Delovno sodišče v Kopru", "Izvršilni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Delovno sodišče v Kopru", "Urad sodišča", "Ferrarska 9", "6000", "Koper"},
{"Delovno sodišče v Kopru - Zunanji oddelek v Novi Gorici", "Delovni oddelek", "Trg Edvarda Kardelja 1", "5000", "Nova Gorica"},
{"Delovno sodišče v Kopru - Zunanji oddelek v Novi Gorici", "Izvršilni oddelek", "Trg Edvarda Kardelja 1", "5000", "Nova Gorica"},
{"Delovno sodišče v Kopru - Zunanji oddelek v Postojni", "Delovni oddelek", "Jenkova 3", "6230", "Postojna"},
{"Delovno sodišče v Kopru - Zunanji oddelek v Postojni", "Izvršilni oddelek", "Jenkova 3", "6230", "Postojna"},
{"Delovno sodišče v Mariboru", "Delovni oddelek", "Glavni trg 17", "2000", "Maribor"},
{"Delovno sodišče v Mariboru", "Izvršilni oddelek", "Glavni trg 17", "2000", "Maribor"},
{"Delovno sodišče v Mariboru", "Urad sodišča", "Glavni trg 17", "2000", "Maribor"},
{"Delovno sodišče v Mariboru - Zunanji oddelek na Ptuju", "Delovni oddelek", "Krempljeva 7", "2250", "Ptuj"},
{"Delovno sodišče v Mariboru - Zunanji oddelek na Ptuju", "Delovni oddelek", "Krempljeva 7", "2250", "Ptuj"},
{"Delovno sodišče v Mariboru - Zunanji oddelek na Ptuju", "Izvršilni oddelek", "Krempljeva 7", "2250", "Ptuj"},
{"Delovno sodišče v Mariboru - Zunanji oddelek v Murski Soboti", "Delovni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Delovno sodišče v Mariboru - Zunanji oddelek v Murski Soboti", "Izvršilni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Delovno sodišče v Mariboru - Zunanji oddelek v Slovenj Gradcu", "Delovni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Delovno sodišče v Mariboru - Zunanji oddelek v Slovenj Gradcu", "Izvršilni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sod. v Ljubljani - centralni oddelek za verodostojno listino", "Centralni odd. za verodostojno listino ", "Zaloška 59", "1000", "Ljubljana"},
{"Okrajno sodišče na Jesenicah", "Gospodarski ", "Titova 37", "4270", "Jesenice "},
{"Okrajno sodišče na Jesenicah", "Izvršilni oddelek", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Jesenicah", "Kazenski odd. - OJ na Jesenicah", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Jesenicah", "Nepravdni oddelek", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Jesenicah", "Pravdni oddelek", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Jesenicah", "R-civilni", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Jesenicah", "Urad sodišča", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Jesenicah", "Zapuščinski oddelek", "Titova 37", "4270", "Jesenice"},
{"Okrajno sodišče na Ptuju", "Izvršilni oddelek", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Ptuju", "Kazenski odd. - OJ na Ptuju", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Ptuju", "Nepravdni oddelek", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Ptuju", "Pravdni oddelek", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Ptuju", "R-civilni", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Ptuju", "Urad sodišča", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Ptuju", "Zapuščinski oddelek", "Vodnikova 2", "2250", "Ptuj"},
{"Okrajno sodišče na Vrhniki", "Izvršilni oddelek", "Vrhnika b.b.", "1000", "Vrhnika"},
{"Okrajno sodišče na Vrhniki", "Kazenski odd. - OJ na Vrhniki", "Cankarjev trg 8", "1360", "Vrhnika"},
{"Okrajno sodišče na Vrhniki", "Nepravdni oddelek", "Cankarjev trg 8", "1360", "Vrhnika"},
{"Okrajno sodišče na Vrhniki", "Pravdni oddelek", "Cankarjev trg 8", "1360", "Vrhnika"},
{"Okrajno sodišče na Vrhniki", "R-civilni", "Cankarjev trg 8", "1360", "Vrhnika"},
{"Okrajno sodišče na Vrhniki", "Urad sodišča", "Cankarjev trg 8", "1360", "Vrhnika"},
{"Okrajno sodišče na Vrhniki", "Zapuščinski oddelek", "Cankarjev trg 8", "1360", "Vrhnika"},
{"Okrajno sodišče v Ajdovščini", "Izvršilni oddelek", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Ajdovščini", "Kazenski odd. - OJ v Ajdovščini", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Ajdovščini", "Nepravdni oddelek", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Ajdovščini", "Pravdni oddelek", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Ajdovščini", "R-civilni", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Ajdovščini", "Urad sodišča", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Ajdovščini", "Zapuščinski oddelek", "Gregorčičeva 28", "5270", "Ajdovščina"},
{"Okrajno sodišče v Brežicah", "Izvršilni oddelek", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Brežicah", "Kazenski odd. - OJ v Brežicah", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Brežicah", "Nepravdni oddelek", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Brežicah", "Pravdni oddelek", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Brežicah", "R-civilni", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Brežicah", "Urad sodišča", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Brežicah", "Zapuščinski oddelek", "Cesta prvih borcev 48", "8250", "Brežice"},
{"Okrajno sodišče v Celju", "Izvršilni oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Celju", "Kazenski odd. - OJ v Celju", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Celju", "Nepravdni oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Celju", "Pravdni oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Celju", "R-civilni", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Celju", "Urad sodišča", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Celju", "Zapuščinski oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrajno sodišče v Cerknici", "Izvršilni oddelek", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Cerknici", "Kazenski odd. - OJ v Cerknici", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Cerknici", "Nepravdni oddelek", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Cerknici", "Pravdni oddelek", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Cerknici", "R-civilni", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Cerknici", "Urad sodišča", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Cerknici", "Zapuščinski oddelek", "Cesta 4. maja 23", "1380", "Cerknica"},
{"Okrajno sodišče v Črnomlju", "Izvršilni oddelek", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Črnomlju", "Kazenski odd. - OJ v Črnomlju", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Črnomlju", "Nepravdni oddelek", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Črnomlju", "Pravdni oddelek", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Črnomlju", "R-civilni", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Črnomlju", "Urad sodišča", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Črnomlju", "Zapuščinski oddelek", "Trg svobode 1", "8340", "Črnomelj"},
{"Okrajno sodišče v Domžalah", "Izvršilni oddelek", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Domžalah", "Kazenski odd. - OJ v Domžalah", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Domžalah", "Nepravdni oddelek", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Domžalah", "Pravdni oddelek", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Domžalah", "R-civilni", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Domžalah", "Urad sodišča", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Domžalah", "Zapuščinski oddelek", "Ljubljanska 76", "1230", "Domžale"},
{"Okrajno sodišče v Gornji Radgoni", "Izvršilni oddelek", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Gornji Radgoni", "Kazenski odd. - OJ v Gornji Radgoni", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Gornji Radgoni", "Nepravdni oddelek", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Gornji Radgoni", "Pravdni oddelek", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Gornji Radgoni", "R-civilni", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Gornji Radgoni", "Urad sodišča", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Gornji Radgoni", "Zapuščinski oddelek", "Kerenčičeva 3", "9250", "Gornja Radgona"},
{"Okrajno sodišče v Grosupljem", "Izvršilni oddelek", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Grosupljem", "Kazenski odd. - OJ v Grosupljem", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Grosupljem", "Nepravdni oddelek", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Grosupljem", "Pravdni oddelek", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Grosupljem", "R-civilni", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Grosupljem", "Urad sodišča", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Grosupljem", "Zapuščinski oddelek", "Adamičeva 6", "1290", "Grosuplje"},
{"Okrajno sodišče v Idriji", "Izvršilni oddelek", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Idriji", "Kazenski odd. - OJ v Idriji", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Idriji", "Nepravdni oddelek", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Idriji", "Pravdni oddelek", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Idriji", "R-civilni", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Idriji", "Urad sodišča", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Idriji", "Zapuščinski oddelek", "Mestni trg 1", "5280", "Idrija"},
{"Okrajno sodišče v Ilirski Bistrici", "Izvršilni oddelek", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Ilirski Bistrici", "Kazenski odd. - OJ v Ilirski Bistrici", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Ilirski Bistrici", "Nepravdni oddelek", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Ilirski Bistrici", "Pravdni oddelek", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Ilirski Bistrici", "R-civilni", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Ilirski Bistrici", "Urad sodišča", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Ilirski Bistrici", "Zapuščinski oddelek", "Bazoviška 22", "6250", "Ilirska Bistrica"},
{"Okrajno sodišče v Kamniku", "Izvršilni oddelek", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kamniku", "Kazenski odd. - OJ v Kamniku", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kamniku", "Nepravdni oddelek", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kamniku", "Pravdni oddelek", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kamniku", "R-civilni", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kamniku", "Urad sodišča", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kamniku", "Zapuščinski oddelek", "Tomšičeva 2", "1241", "Kamnik"},
{"Okrajno sodišče v Kočevju", "Izvršilni oddelek", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kočevju", "Kazenski odd. - OJ v Kočevju", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kočevju", "Nepravdni oddelek", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kočevju", "Pravdni oddelek", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kočevju", "R-civilni", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kočevju", "Urad sodišča", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kočevju", "Zapuščinski oddelek", "Ljubljanska 26", "1330", "Kočevje"},
{"Okrajno sodišče v Kopru", "Izvršilni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kopru", "Kazenski oddelek - OJ v Kopru", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kopru", "Nepravdni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kopru", "Pravdni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kopru", "R-civilni", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kopru", "Urad sodišča", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kopru", "Zapuščinski oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrajno sodišče v Kranju", "Izvršilni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Kranju", "Kazenski odd. - OJ v Kranju", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Kranju", "Nepravdni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Kranju", "Pravdni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Kranju", "R-civilni", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Kranju", "Urad sodišča", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Kranju", "Zapuščinski oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrajno sodišče v Krškem", "Izvršilni oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Krškem", "Kazenski odd. - OJ v Krškem", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Krškem", "Nepravdni oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Krškem", "Pravdni oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Krškem", "R-civilni", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Krškem", "Urad sodišča", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Krškem", "Zapuščinski oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrajno sodišče v Lenartu", "Izvršilni oddelek", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lenartu", "Kazenski odd. - OJ v Lenartu", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lenartu", "Nepravdni oddelek", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lenartu", "Pravdni oddelek", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lenartu", "R-civilni", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lenartu", "Urad sodišča", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lenartu", "Zapuščinski oddelek", "Jurovska cesta 15", "2230", "Lenart"},
{"Okrajno sodišče v Lendavi", "Izvršilni oddelek", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Lendavi", "Kazenski odd. - OJ v Lendavi", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Lendavi", "Nepravdni oddelek", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Lendavi", "Pravdni oddelek", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Lendavi", "R-civilni", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Lendavi", "Urad sodišča", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Lendavi", "Zapuščinski oddelek", "Glavna ulica 9", "9220", "Lendava"},
{"Okrajno sodišče v Litiji", "Izvršilni oddelek", "Jerebova 6", "1270", "Litija"},
{"Okrajno sodišče v Litiji", "Kazenski odd. - OJ v Litiji", "Jerebova 6", "1270", "Litija"},
{"Okrajno sodišče v Litiji", "Nepravdni oddelek", "Jerebova 8", "1270", "Litija"},
{"Okrajno sodišče v Litiji", "Pravdni oddelek", "Jerebova 8", "1270", "Litija"},
{"Okrajno sodišče v Litiji", "R-civilni", "Jerebova 8", "1270", "Litija"},
{"Okrajno sodišče v Litiji", "Urad sodišča", "Jerebova 6", "1270", "Litija"},
{"Okrajno sodišče v Litiji", "Zapuščinski oddelek", "Jerebova 8", "1270", "Litija"},
{"Okrajno sodišče v Ljubljani", "Finančna služba", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Finančno računovodstvo", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Izvršilni oddelek", "Miklošičeva ul. 10", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Kazenski oddelek", "Mali trg 6", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Mediacijski oddelek", "Miklošičeva 12", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Nepravdni in zapuščinski oddelek", "Miklošičeva 12", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Pravdni oddelek", "Miklošičeva 12", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Prekrškovni oddelek", "Mala ulica 3", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "R-civilni", "Miklošičeva 12", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Skupna kadrovska služba", "Miklošičeva 12", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Sprejemna pisarna", "Miklošičeva 10", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Urad predsednice", "Miklošičeva 10", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Vložišče", "Miklošičeva 10", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Zapuščinski oddelek", "Miklošičeva 12", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljubljani", "Zemljiškoknjižni oddelek", "Miklošičeva 10", "1000", "Ljubljana"},
{"Okrajno sodišče v Ljutomeru", "Izvršilni oddelek", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Ljutomeru", "Kazenski odd. - OJ v Ljutomeru", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Ljutomeru", "Nepravdni oddelek", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Ljutomeru", "Pravdni oddelek", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Ljutomeru", "R-civilni", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Ljutomeru", "Urad sodišča", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Ljutomeru", "Zapuščinski oddelek", "Prešernova 18", "9240", "Ljutomer"},
{"Okrajno sodišče v Mariboru", "Izvršilni oddelek", "Sodna 14", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "Kazenski odd. - OJ v Mariboru", "Cafova 1", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "Nepravdni oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "Pravdni oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "R-civilni", "Sodna ulica 14", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "Urad sodišča", "Sodna ulica 14", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "Zapuščinski oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Okrajno sodišče v Mariboru", "Zemljiška knjiga", "Sodna ulica 14", "2503", "Maribor"},
{"Okrajno sodišče v Murski Soboti", "Izvršilni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Murski Soboti", "Kazenski odd. - OJ v Murski Soboti", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Murski Soboti", "Nepravdni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Murski Soboti", "Pravdni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Murski Soboti", "R-civilni", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Murski Soboti", "Urad sodišča", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Murski Soboti", "Zapuščinski oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrajno sodišče v Novem mestu", "Izvršilni oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novem mestu", "Kazenski odd. - OJ v Novem mestu", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novem mestu", "Nepravdni oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novem mestu", "Pravdni oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novem mestu", "R-civilni", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novem mestu", "Urad sodišča", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novem mestu", "Zapuščinski oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrajno sodišče v Novi Gorici", "Izvršilni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrajno sodišče v Novi Gorici", "Kazenski oddelek - OJ v Novi Gorici", "Prvomajska 50", "5000", "Nova Gorica"},
{"Okrajno sodišče v Novi Gorici", "Nepravdni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrajno sodišče v Novi Gorici", "Pravdni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrajno sodišče v Novi Gorici", "R-civilni", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrajno sodišče v Novi Gorici", "Urad sodišča", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrajno sodišče v Novi Gorici", "Zapuščinski oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrajno sodišče v Ormožu", "Izvršilni oddelek", "Vrazova 9", "2270", "Ormož"},
{"Okrajno sodišče v Ormožu", "Kazenski odd. - OJ v Ormožu", "Ptujska cesta 8c", "2270", "Ormož"},
{"Okrajno sodišče v Ormožu", "Nepravdni oddelek", "Ptujska cesta 8c", "2270", "Ormož"},
{"Okrajno sodišče v Ormožu", "Pravdni oddelek", "Ptujska cesta 8c", "2270", "Ormož"},
{"Okrajno sodišče v Ormožu", "R-civilni", "Ptujska cesta 8c", "2270", "Ormož"},
{"Okrajno sodišče v Ormožu", "Urad sodišča", "Ptujska cesta 8c", "2270", "Ormož"},
{"Okrajno sodišče v Ormožu", "Zapuščinski oddelek", "Ptujska cesta 8c", "2270", "Ormož"},
{"Okrajno sodišče v Piranu", "Izvršilni oddelek", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Piranu", "Kazenski odd. - OJ v Piranu", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Piranu", "Nepravdni oddelek", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Piranu", "Pravdni oddelek", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Piranu", "R-civilni", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Piranu", "Urad sodišča", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Piranu", "Zapuščinski oddelek", "Tartinijev trg 1", "6330", "Piran"},
{"Okrajno sodišče v Postojni", "Izvršilni oddelek", "Jenkova 1", "6230", "Postojna"},
{"Okrajno sodišče v Postojni", "Kazenski odd. - OJ v Postojni", "Jenkova 3", "6230", "Postojna"},
{"Okrajno sodišče v Postojni", "Nepravdni oddelek", "Jenkova 1", "6230", "Postojna"},
{"Okrajno sodišče v Postojni", "Pravdni oddelek", "Jenkova 1", "6230", "Postojna"},
{"Okrajno sodišče v Postojni", "R-civilni", "Jenkova 1", "6230", "Postojna"},
{"Okrajno sodišče v Postojni", "Urad sodišča", "Jenkova 3", "6230", "Postojna"},
{"Okrajno sodišče v Postojni", "Zapuščinski oddelek", "Jenkova 1", "6230", "Postojna"},
{"Okrajno sodišče v Radovljici", "Izvršilni oddelek", "Gorenjska c. 5", "4240", "Radovljica"},
{"Okrajno sodišče v Radovljici", "Kazenski odd. - OJ v Radovljici", "Gorenjska c. 15", "4240", "Radovljica"},
{"Okrajno sodišče v Radovljici", "Nepravdni oddelek", "Gorenjska c. 15", "4240", "Radovljica"},
{"Okrajno sodišče v Radovljici", "Pravdni oddelek", "Gorenjska c. 15", "4240", "Radovljica"},
{"Okrajno sodišče v Radovljici", "R-civilni", "Gorenjska c. 15", "4240", "Radovljica"},
{"Okrajno sodišče v Radovljici", "Urad sodišča", "Gorenjska c. 15", "4240", "Radovljica"},
{"Okrajno sodišče v Radovljici", "Zapuščinski oddelek", "Gorenjska c. 15", "4240", "Radovljica"},
{"Okrajno sodišče v Sevnici", "Izvršilni oddelek", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sevnici", "Kazenski odd. - OJ v Sevnici", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sevnici", "Nepravdni oddelek", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sevnici", "Pravdni oddelek", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sevnici", "R-civilni", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sevnici", "Urad sodišča", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sevnici", "Zapuščinski oddelek", "Glavni trg 30", "8290", "Sevnica"},
{"Okrajno sodišče v Sežani", "Izvršilni oddelek", "Sežana", "6210", "Sežana"},
{"Okrajno sodišče v Sežani", "Kazenski odd. - OJ v Sežani", "Kosovelova 1", "6210", "Sežana"},
{"Okrajno sodišče v Sežani", "Nepravdni oddelek", "Kosovelova 1", "6210", "Sežana"},
{"Okrajno sodišče v Sežani", "Pravdni oddelek", "Kosovelova 1", "6210", "Sežana"},
{"Okrajno sodišče v Sežani", "R-civilni", "Kosovelova 1", "6210", "Sežana"},
{"Okrajno sodišče v Sežani", "Urad sodišča", "Kosovelova 1", "6210", "Sežana"},
{"Okrajno sodišče v Sežani", "Zapuščinski oddelek", "Kosovelova 1", "6210", "Sežana"},
{"Okrajno sodišče v Slovenj Gradcu", "Izvršilni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "Kazenski odd. - OJ v Slovenj Gradcu", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "Nepravdni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "Pravdni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "Prekrškovni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "R-civilni", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "Urad sodišča", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenj Gradcu", "Zapuščinski oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrajno sodišče v Slovenski Bistrici", "Izvršilni oddelek", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenski Bistrici", "Kazenski odd. - OJ v Slovenski Bistrici", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenski Bistrici", "Nepravdni oddelek", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenski Bistrici", "Pravdni oddelek", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenski Bistrici", "R-civilni", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenski Bistrici", "Urad sodišča", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenski Bistrici", "Zapuščinski oddelek", "Kolodvorska 10", "2310", "Slovenska Bistrica"},
{"Okrajno sodišče v Slovenskih Konjicah", "Izvršilni oddelek", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Slovenskih Konjicah", "Kazenski odd. - OJ v Slovenskih Konjicah", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Slovenskih Konjicah", "Nepravdni oddelek", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Slovenskih Konjicah", "Pravdni oddelek", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Slovenskih Konjicah", "R-civilni", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Slovenskih Konjicah", "Urad sodišča", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Slovenskih Konjicah", "Zapuščinski oddelek", "Mestni trg 6", "3210", "Slovenske Konjice"},
{"Okrajno sodišče v Šentjurju ", "Delovni oddelek", "X", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "Izvršilni oddelek", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "Kazenski odd. - OJ v Šentjurju", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "Nepravdni oddelek", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "Pravdni oddelek", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "R-civilni", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "Urad sodišča", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Šentjurju ", "Zapuščinski oddelek", "Dušana Kvedra 45", "3230", "Šentjur"},
{"Okrajno sodišče v Škofji Loki", "Izvršilni oddelek", "Šolska 4", "4220", "Škofja Loka"},
{"Okrajno sodišče v Škofji Loki", "Kazenski odd. - OJ v Škofji Loki", "Partizanska cesta 1a", "4220", "Škofja Loka"},
{"Okrajno sodišče v Škofji Loki", "Nepravdni oddelek", "Partizanska cesta 1a", "4220", "Škofja Loka"},
{"Okrajno sodišče v Škofji Loki", "Pravdni oddelek", "Partizanska cesta 1a", "4220", "Škofja Loka"},
{"Okrajno sodišče v Škofji Loki", "R-civilni", "Partizanska cesta 1a", "4220", "Škofja Loka"},
{"Okrajno sodišče v Škofji Loki", "Urad sodišča", "Partizanska cesta 1a", "4220", "Škofja Loka"},
{"Okrajno sodišče v Škofji Loki", "Zapuščinski oddelek", "Partizanska cesta 1a", "4220", "Škofja Loka"},
{"Okrajno sodišče v Šmarju pri Jelšah", "Izvršilni oddelek", "Trg A. Aškerca 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Šmarju pri Jelšah", "Kazenski odd. - OJ v Šmarju pri Jelšah", "Aškerčev trg 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Šmarju pri Jelšah", "Nepravdni oddelek", "Trg A. Aškerca 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Šmarju pri Jelšah", "Pravdni oddelek", "Trg A. Aškerca 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Šmarju pri Jelšah", "R-civilni", "Trg A. Aškerca 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Šmarju pri Jelšah", "Urad sodišča", "Aškerčev trg 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Šmarju pri Jelšah", "Zapuščinski oddelek", "Trg A. Aškerca 11", "3240", "Šmarje pri Jelšah"},
{"Okrajno sodišče v Tolminu", "Izvršilni oddelek", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Tolminu", "Kazenski odd. - OJ v Tolminu", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Tolminu", "Nepravdni oddelek", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Tolminu", "Pravdni oddelek", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Tolminu", "R-civilni", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Tolminu", "Urad sodišča", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Tolminu", "Zapuščinski oddelek", "Mestni trg 1", "5220", "Tolmin"},
{"Okrajno sodišče v Trbovljah", "Izvršilni oddelek", "Trg revolucije 11", "1420", "Trbovlje"},
{"Okrajno sodišče v Trbovljah", "Kazenski odd. - OJ v Trbovljah", "Trg revolucije 11", "1420", "Trbovlje"},
{"Okrajno sodišče v Trbovljah", "Nepravdni oddelek", "Trg revolucije 11", "1420", "Trbovlje"},
{"Okrajno sodišče v Trbovljah", "Pravdni oddelek", "Trg revolucije 11", "1420", "Trbovlje"},
{"Okrajno sodišče v Trbovljah", "R-civilni", "Trg revolucije 11", "1420", "Trbovlje"},
{"Okrajno sodišče v Trbovljah", "Urad sodišča", "Rudarska 8", "1420", "Trbovlje"},
{"Okrajno sodišče v Trbovljah", "Zapuščinski oddelek", "Trg revolucije 11", "1420", "Trbovlje"},
{"Okrajno sodišče v Trebnjem", "Izvršilni oddelek", "Gubčeve brigade 9", "8210", "Trebnje"},
{"Okrajno sodišče v Trebnjem", "Kazenski odd. - OJ v Trebnjem", "Gubčeva cesta 9", "8210", "Trebnje"},
{"Okrajno sodišče v Trebnjem", "Nepravdni oddelek", "Gubčeve brigade 9", "8210", "Trebnje"},
{"Okrajno sodišče v Trebnjem", "Pravdni oddelek", "Gubčeve brigade 9", "8210", "Trebnje"},
{"Okrajno sodišče v Trebnjem", "R-civilni", "Gubčeve brigade 9", "8210", "Trebnje"},
{"Okrajno sodišče v Trebnjem", "Urad sodišča", "Gubčeva cesta 9", "8210", "Trebnje"},
{"Okrajno sodišče v Trebnjem", "Zapuščinski oddelek", "Gubčeve brigade 9", "8210", "Trebnje"},
{"Okrajno sodišče v Velenju", "Izvršilni oddelek", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Velenju", "Kazenski odd. - OJ v Velenju", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Velenju", "Nepravdni oddelek", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Velenju", "Pravdni oddelek", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Velenju", "R-civilni", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Velenju", "Urad sodišča", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Velenju", "Zapuščinski oddelek", "Prešernova 1", "3320", "Velenje"},
{"Okrajno sodišče v Žalcu", "Izvršilni oddelek", "Levstikova 14", "3310", "Žalec"},
{"Okrajno sodišče v Žalcu", "Kazenski odd. - OJ v Žalcu", "Levstikova 14", "3310", "Žalec"},
{"Okrajno sodišče v Žalcu", "Nepravdni oddelek", "Levstikova 14", "3310", "Žalec"},
{"Okrajno sodišče v Žalcu", "Pravdni oddelek", "Levstikova 14", "3310", "Žalec"},
{"Okrajno sodišče v Žalcu", "R-civilni", "Levstikova 14", "3310", "Žalec"},
{"Okrajno sodišče v Žalcu", "Urad sodišča", "Levstikova 14", "3310", "Žalec"},
{"Okrajno sodišče v Žalcu", "Zapuščinski oddelek", "Levstikova 14", "3310", "Žalec"},
{"Okrožno sodišče na Ptuju", "Brezplačna pravna pomoč", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Gospodarski oddelek ", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Izvršilni oddelek", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Kazenski odd. - OZ na Ptuju", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Nepravdni oddelek", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Overjanje javnih listin", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Pravdni oddelek", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "R-civilni", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče na Ptuju", "Urad sodišča", "Krempljeva 7", "2250", "Ptuj"},
{"Okrožno sodišče v Celju", "Brezplačna pravna pomoč", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Gospodarski oddelek", "Prešermova 22", "3000", "Celje "},
{"Okrožno sodišče v Celju", "Izvršilni oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Kazenski odd. - OZ v Celju", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Nepravdni oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Overjanje javnih listin", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Pravdni oddelek", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "R-civilni", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Služba za alternativno reševanje sporov", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Celju", "Urad sodišča", "Prešernova 22", "3000", "Celje"},
{"Okrožno sodišče v Kopru", "Brezplačna pravna pomoč", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Gospodarski oddelek", "Ferrarska 9", "6000", "Koper "},
{"Okrožno sodišče v Kopru", "Izvršilni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Kazenski oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Nepravdni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Overjanje javnih listin", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Pravdni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "R-civilni", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Služba za alternativno reševanje sporov", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Urad sodišča", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kopru", "Zapuščine", "Ferrarska 9", "6000", "Koper"},
{"Okrožno sodišče v Kranju", "Brezplačna pravna pomoč", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Gospodarski oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Izvršilni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Kazenski oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Nepravdni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Overjanje javnih listin", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Pravdni oddelek", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "R-civilni", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Kranju", "Urad sodišča", "Zoisova 2", "4000", "Kranj"},
{"Okrožno sodišče v Krškem", "Brezplačna pravna pomoč", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Gospodarski oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Izvršilni oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Kazenski odd. - OZ v Krškem", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Nepravdni oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Overjanje javnih listin", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Pravdni oddelek", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "R-civilni", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Krškem", "Urad sodišča", "Cesta krških žrtev 12", "8270", "Krško"},
{"Okrožno sodišče v Ljubljani", "Arhiv", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Brezplačna pravna pomoč", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Finančno računovodska služba", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Finančno računovodstvo", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Izvršilni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Kadrovsko pravna služba", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Kazenski oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Nepravdni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Oddelek za gospodarsko sodstvo", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "oddelek za pomoč", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Odlk. za gosp.  sod., Stečajna pisarna", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Overjanje javnih listin", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Pravdni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Pravdni oddelek, mednarodne overitve", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "R-civilni", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Služba za alternativno reševanje sporov", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Tehnična služba in ekonomat", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Ljubljani", "Urad predsednika", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Okrožno sodišče v Mariboru", "Brezplačna pravna pomoč", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Gospodarski oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Izvršilni oddelek", "Sodna 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Kazenski odd. - OZ v Mariboru", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Nepravdni oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Overjanje javnih listin", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Pravdni oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "R-civilni", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Služba za alternativno reševanje sporov", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Mariboru", "Urad sodišča", "Sodna ulica 14", "2000", "Maribor"},
{"Okrožno sodišče v Murski Soboti", "Brezplačna pravna pomoč", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Gospodarski oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Izvršilni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Kazenski odd. - OZ v Murski Soboti", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Nepravdni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Overjanje javnih listin", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Pravdni oddelek", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "R-civilni", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Murski Soboti", "Urad sodišča", "Slomškova 21", "9000", "Murska Sobota"},
{"Okrožno sodišče v Novem mestu", "Brezplačna pravna pomoč", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "Gospodarski oddelek ", "Jerebova 2", "8000", "Novo mesto "},
{"Okrožno sodišče v Novem mestu", "Izvršilni oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "Kazenski odd. - OZ v Novem mestu", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "Nepravdni oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "Overjanje javnih listin", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "Pravdni oddelek", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "R-civilni", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novem mestu", "Urad sodišča", "Jerebova 2", "8000", "Novo mesto"},
{"Okrožno sodišče v Novi Gorici", "Brezplačna pravna pomoč", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Gospodarski oddelek ", "Kidričeva 14", "5000", "Nova Gorica "},
{"Okrožno sodišče v Novi Gorici", "Izvršilni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Kazenski oddelek", "Tav?arjeva 9", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Nepravdni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Overjanje javnih listin", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Pravdni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "R-civilni", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Služba za alternativno reševanje sporov", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Novi Gorici", "Urad sodišča", "Kidričeva 14", "5000", "Nova Gorica"},
{"Okrožno sodišče v Slovenj Gradcu", "Brezplačna pravna pomoč", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Gospodarski oddelek", "Kodričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Izvršilni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Kazenski odd. - OZ v Slovenj Gradcu", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Nepravdni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Overjanje javnih listin", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Pravdni oddelek", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "R-civilni", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Okrožno sodišče v Slovenj Gradcu", "Urad sodišča", "Kidričeva 1", "2380", "Slovenj Gradec"},
{"Socialni-Višje delovno in socialno sodišče v Ljubljani", "Delovni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Socialni-Višje delovno in socialno sodišče v Ljubljani", "Delovni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Socialni-Višje delovno in socialno sodišče v Ljubljani", "Izvršilni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Socialni-Višje delovno in socialno sodišče v Ljubljani", "Socialni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Upravno sodišče RS oddelek v Celju", "Izvršilni oddelek", "Prešernova 22", "3000", "Celje"},
{"Upravno sodišče RS oddelek v Celju", "Upravni oddelek", "Trg celjskih knezov 10", "3000", "Celje"},
{"Upravno sodišče RS oddelek v Mariboru", "BP", "Zaloška 59", "1000", "Ljubljana"},
{"Upravno sodišče RS oddelek v Mariboru", "Izvršilni oddelek", "Sodna 14", "2000", "Maribor"},
{"Upravno sodišče RS oddelek v Mariboru", "Upravni oddelek", "Ulica Vita Kraigherja 5", "2000", "Maribor"},
{"Upravno sodišče RS oddelek v Novi Gorici", "Izvršilni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Upravno sodišče RS oddelek v Novi Gorici", "Upravni oddelek", "Kidričeva 14", "5000", "Nova Gorica"},
{"Upravno sodišče RS v Ljubljani", "BP", "Zaloška 59", "1000", "Ljubljana"},
{"Upravno sodišče RS v Ljubljani", "Izvršilni oddelek", "Tržaška cesta 68 a", "1000", "Ljubljana"},
{"Upravno sodišče RS v Ljubljani", "Upravni oddelek", "Tržaška 68a", "1000", "Ljubljana"},
{"Upravno sodišče RS v Ljubljani", "Urad sodišča", "Tržaška cesta 68 a", "1000", "Ljubljana"},
{"Višje delovno in socialno sodišče v Ljubljani", "Delovni oddelek", "Dunajska 22", "1000", "Ljubljana"},
{"Višje delovno in socialno sodišče v Ljubljani", "Izvršilni oddelek", "Resljeva 14", "1000", "Ljubljana"},
{"Višje delovno in socialno sodišče v Ljubljani", "Socialni oddelek", "Dunajska 22", "1000", "Ljubljana"},
{"Višje delovno in socialno sodišče v Ljubljani", "Urad sodišča", "Dunajska 22", "1000", "Ljubljana"},
{"Višje sodišče v Celju", "Gospodarski oddelek", "Prešernova 22", "3000", "Celje"},
{"Višje sodišče v Celju", "Izvršilni oddelek", "Prešernova 22", "3000", "Celje"},
{"Višje sodišče v Celju", "Kazenski odd. - VS v Celju", "Prešernova 22", "3000", "Celje"},
{"Višje sodišče v Celju", "Pravdni oddelek", "Prešernova 22", "3000", "Celje"},
{"Višje sodišče v Celju", "Urad sodišča", "Prešernova 22", "3000", "Celje"},
{"Višje sodišče v Celju", "Zemljiška knjiga", "x", "3000", "celje"},
{"Višje sodišče v Kopru", "Gospodarski oddelek", "Ferrarska 9", "6000", "Koper"},
{"Višje sodišče v Kopru", "Izvršilni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Višje sodišče v Kopru", "Kazenski oddelek", "Ferarska 9", "6000", "Koper"},
{"Višje sodišče v Kopru", "Pravdni oddelek", "Ferrarska 9", "6000", "Koper"},
{"Višje sodišče v Kopru", "Urad sodišča", "Ferrarska 9", "6000", "Koper"},
{"Višje sodišče v Ljubljani", "eRačuni", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Finančna služba", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Finančno računovodstvo", "Miklošičeva 4", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Gospodarski oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Gospodarski oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Izvršilni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Kadrovska služba", "Miklošičeva 4", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Kazenski oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Mediacije", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Pravdni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Urad sodišča", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Višje sodišče v Ljubljani", "Zemljiška knjiga", "x", "1000", "Ljubljana"},
{"Višje sodišče v Mariboru", "Gospodarski oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Višje sodišče v Mariboru", "Izvršilni oddelek", "Sodna 14", "2000", "Maribor"},
{"Višje sodišče v Mariboru", "Kazenski odd. - VS v Mariboru", "Sodna ulica 14", "2000", "Maribor"},
{"Višje sodišče v Mariboru", "Pravdni oddelek", "Sodna ulica 14", "2000", "Maribor"},
{"Višje sodišče v Mariboru", "Urad sodišča", "Sodna ulica 14", "2000", "Maribor"},
{"Vrhovno sodišče RS", "Center za informatiko", "Miklošičeva 4", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Centralna pravosodna knjižnica", "Tavčarjeva 9", "1000", "Ljubljana "},
{"Vrhovno sodišče RS", "Civilni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Del.soc. oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Evidenčni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Finančno računovodstvo", "Miklošičeva 4", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Gospodarski oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Izvršilni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Kazenski oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Pisarna za spl. in str. -tehnične zadeve", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Skupna finančna služba", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Skupna kadrovska služba", "Miklošičeva 4", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Služba za notranjo revizijo (SNRS)", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Služba za odnose z javnostmi in prom.", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Služba za razvoj SU (SRSU)", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Sprejemna pisarna", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Tehnična služba in ekonomat", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Upravni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS", "Urad predsednika", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS- I Up", "Upravni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS-del.soc", "Del.soc. oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS-del.soc", "Del.soc. oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS-del.soc", "Izvršilni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"},
{"Vrhovno sodišče RS-del.soc", "Upravni oddelek", "Tavčarjeva 9", "1000", "Ljubljana"}
  } ;
  
  
  
  public static String[] SENDER_NAMES = new String[]{
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Trebnjem",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Mariboru",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Krškem",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Postojni",
        "Okrajno sodišče v Postojni, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Sevnici",
        "Okrajno sodišče v Trbovljah, Izvršilni oddelek ",
        "Okrajno sodišče v Slovenj Gradcu, Izvršilni oddelek ",
        "Okrajno sodišče v Domžalah, Izvršilni oddelek ",
        "Okrajno sodišče v Radovljici ", "Okrajno sodišče v Postojni ",
        "Okrajno sodišče v Šmarju pri Jelšah, Izvršilni oddelek ",
        "Okrajno sodišče v Trebnjem ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Kočevju",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Šentjurju ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Litiji",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Novi Gorici",
        "Okrajno sodišče v Krškem, Izvršilni oddelek ",
        "Okrajno sodišče v Črnomlju, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Brežicah",
        "Okrajno sodišče v Mariboru ",
        "Okrajno sodišče v Ajdovščini, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Piranu",
        "Okrajno sodišče v Trbovljah ",
        "Okrajno sodišče na Ptuju ",
        "Okrajno sodišče v Piranu, Izvršilni oddelek ",
        "Okrajno sodišče v Žalcu, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče na Jesenicah",
        "Okrajno sodišče v Šentjurju ",
        "Okrajno sodišče v Škofji Loki ", "Okrajno sodišče v Kočevju ",
        "Okrajno sodišče v Slovenski Bistrici, Izvršilni oddelek ",
        "Okrajno sodišče v Gornji Radgoni, Izvršilni oddelek ",
        "Okrajno sodišče v Kočevju, Izvršilni oddelek ",
        "Okrajno sodišče v Brežicah ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Ajdovščini",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Kopru",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Ljubljani",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Kranju",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Lendavi",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Cerknici",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Sežani",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Slovenj Gradcu",
        "Okrajno sodišče na Ptuju, Izvršilni oddelek ",
        "Okrajno sodišče v Lendavi, Izvršilni oddelek ",
        "Okrajno sodišče v Slovenj Gradcu ",
        "Okrajno sodišče v Mariboru, Izvršilni oddelek ",
        "Okrajno sodišče v Grosupljem ",
        "Okrajno sodišče v Murski Soboti, Izvršilni oddelek ",
        "Okrajno sodišče v Ljutomeru, Izvršilni oddelek ",
        "Okrajno sodišče v Radovljici, Izvršilni oddelek ",
        "Okrajno sodišče v Sevnici ", "Okrajno sodišče v Ilirski Bistrici ",
        "Okrajno sodišče v Trebnjem, Izvršilni oddelek ",
        "Okrajno sodišče v Tolminu ", "Okrajno sodišče v Šentjurju  ",
        "Okrajno sodišče v Gornji Radgoni ",
        "Okrajno sodišče v Brežicah, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Celju",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Slovenski Bistrici",
        "Okrajno sodišče v Kamniku ", "Okrajno sodišče v Lenartu ",
        "Okrajno sodišče v Novi Gorici, Izvršilni oddelek ",
        "Okrajno sodišče na Jesenicah, Izvršilni oddelek ",
        "Okrajno sodišče v Slovenski Bistrici ",
        "Okrajno sodišče v Kopru ",
        "Okrajno sodišče v Škofji Loki, Izvršilni oddelek ",
        "Okrajno sodišče v Sežani, Izvršilni oddelek ",
        "Okrajno sodišče v Kopru, Izvršilni oddelek ",
        "Okrajno sodišče v Piranu ",
        "Okrajno sodišče v Lenartu, Izvršilni oddelek ",
        "Okrajno sodišče na Vrhniki ",
        "Okrajno sodišče v Novi Gorici ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Gornji Radgoni",
        "Okrajno sodišče v Domžalah ", "Okrajno sodišče v Slovenskih Konjicah ",
        "Okrajno sodišče v Ilirski Bistrici, Izvršilni oddelek ",
        "Okrajno sodišče v Sežani ",
        "Okrajno sodišče v Cerknici, Izvršilni oddelek ",
        "Okrajno sodišče v Idriji ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Velenju",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Kamniku",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Šmarju pri Jelšah",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Murski Soboti",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Škofji Loki",
        "Okrajno sodišče v Novem mestu, Izvršilni oddelek ",
        "Okrajno sodišče v Celju, Izvršilni oddelek ",
        "Okrajno sodišče v Murski Soboti ",
        "Okrajno sodišče v Litiji, Izvršilni oddelek ",
        "Okrajno sodišče v Slovenskih Konjicah, Izvršilni oddelek ",
        "Okrajno sodišče na Vrhniki, Izvršilni oddelek ",
        "Okrajno sodišče v Ormožu, Izvršilni oddelek ",
        "Okrajno sodišče v Cerknici ", "Okrajno sodišče v Litiji ",
        "Okrajno sodišče v Lendavi ", "Okrajno sodišče v Novem mestu ",
        "Okrajno sodišče v Tolminu, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče na Ptuju",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Žalcu",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Domžalah",
        "Okrajno sodišče v Velenju, Izvršilni oddelek ",
        "Okrajno sodišče v Šmarju pri Jelšah ",
        "Okrajno sodišče v Velenju ", "Okrajno sodišče v Celju ",
        "Okrajno sodišče v Krškem ",
        "Okrajno sodišče v Ljutomeru ", "Okrajno sodišče v Ajdovščini ",
        "Okrajno sodišče v Idriji, Izvršilni oddelek ",
        "Okrajno sodišče v Ormožu ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Novem mestu",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Radovljici",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Lenartu",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Črnomlju",
        "Okrajno sodišče v Ljubljani, Izvršilni oddelek ",
        "Okrajno sod. v Ljubljani - centralni oddelek za verodostojno listino ",
        "Okrajno sodišče v Kranju ",
        "Okrajno sodišče na Jesenicah ",
        "Okrajno sodišče v Šentjurju, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče na Vrhniki",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Šentjurju",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Trbovljah",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Slovenskih Konjicah",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sod. v Ljubljani - centralni oddelek za verodostojno listino",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Ljutomeru",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Idriji",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Grosupljem",
        "Okrajno sodišče v Kranju, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Ormožu",
        "Okrajno sodišče v Črnomlju ",
        "Okrajno sodišče v Kamniku, Izvršilni oddelek ",
        "Okrajno sodišče v Ljubljani ",
        "Okrajno sodišče v Sevnici, Izvršilni oddelek ",
        "Okrajno sodišče v Žalcu ",
        "Okrajno sodišče v Grosupljem, Izvršilni oddelek ",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Ilirski Bistrici",
        "Vrhovno sodišče - Informacijski sistem eIzvršba Okrajno sodišče v Tolminu"};
    public static String[] SUBJECTS = new String[]{
        "dopis z dne 29.3.2016, PRAVN. SKLEP O ZVRŠBI",
        "sklep 23.03.2016,dgp.odg.na ug.s pril.z dne 21.12.2015",
        "P60_23, sklep št.III D 459/13 (priloga C8)",
        "r.št. 25 s kl.prav.", "dopis o poplačilu, dgp. vloge r. 12",
        "sklep o nadaljevanju izvršbe-86+predlog-82+pril.",
        "pozivni sklep U z drugop. r. št. 12", "Stroški IZV z r.št. 11 s pril. ",
        "dopis  25.3.2016 z r.št. 6",
        "Sklep z dne 18.3.2016,ftc.u.z. z dne 2.10.2014",
        "skl. str. izv. z dne 21.3.16 z vl. z dne 3.3.16 s strošk.",
        "sklep  24.3.2016 s predl., dopis 24.3.16",
        "sklep 23.3.2016 + dgp. vl. 21.1.16",
        "Dopis z dne 30. 03. 2016 s pril. ",
        "S59_S590452__23326 odgovor na ugovor s prilogami",
        "Sklep o izvršbi s pred. in pril., dopol. pred. s pril.",
        "skl. nis opp. + str.,pi,prnm si,ftk.predlog za nis ",
        "Sklep 21.3.2016+vloga 12.2.2016+14.3.2016",
        "sklep z dne 29. 3. 2016 s prilogami",
        "sklep z dne 29. 3. 2016 s prilogo",
        "sklep 23.3.2016, vl. 16.9.2015, rtr", "sklep NIS OPP s pril.",
        "Dopis upniku + VL. IZVR. Z DNE 19.2.16",
        "obv.pnm.  Skl.NIS.pl.  dopis,ftk.l.50,pnm.IS+IP,skl.l.41-,43-",
        "ftk.l.56 v vednost", "SKLEP 17.3.16 + FTK. SPISA",
        "Predlog-izvršba VL,SO sklep o izvršbi",
        "sklep- sprememba upnika  in vlogau pnika 15.12.2015", "prm.ID+RTRR",
        "Sklep N.I.S.-23 S00_0120vl. 19, prav. skl. o izv. s pr., r. 9,11",
        "Predložitveno poročilo, spis I 291/2014",
        "sklep o izvršbi in predlog s pril.",
        "dopis z dne 30.3.2016, vrač. skl. o del.ust.z dne 21.12.2015",
        "prav. skl. 21", "poziv izv ",
        "Odredba 29.03.2016 (VROČ.2), Sklep 29.03.2016 (VROČ.3) + Sodno pismo",
        "S00_0197", "dopis 18.3.16+skl. 15.3.16+vl. 26.2.16+ZZZS",
        "skl. 15.3.16+vl. 26.2.16+RTR+ZZZS", "Vloga 7.3.2016",
        "dopis 25.3.16  obv. o pravn. 25.3.16", "obvestilo o popl. dolga",
        "dopis z dne 29.3.16, drug.ug. z dne 1.3.16 s pril.", "Vloga",
        "sklep, obrazec ZST-1",
        "prav. skl. o izv. s pr., r. 5,19", "odredba z dne 29.3.2016",
        "sklep z dne 25.3.2016",
        "Sklep 21.3.16, sklep 18.11.15 s prav., 23.6.15 s prav.",
        "soi z dne 25.3.16, ip z dne 9.2.16 s pril.",
        "dopis z dne 29.3.2016, fot.vloge z dne 28.1.2016 - v vednost",
        "Sklep z dne 24. 3. 2016 +l. 13 (2)",
        "prm.skl. 9.2.16", "dopis prim.b., ftk. l. 13,22",
        "dopis 24.3.16+vl. 22.+25.2.+17.3.16",
        "PNM sklep z dne 4.2.2016 (1)",
        "dopis z dne 25.3.2016, vl. OPP 23.7.2015", "2xodr., orig. rač. ",
        "sklep z dne 25.3.2016 + pravn. sklep o izvršbi in predlog",
        "sklep o umiku z dne 25.3.2016",
        "pravn. sklep z dne 2.3.16, ftk. spisa", "skl. o um. 21.3.",
        "Dopis z dne 25.3.2016 +l. 23 (2)",
        "sklep o določ.", "dopis z dne 25.3.2016 in vloga z dne 10.2.2016",
        "sklep o novem upniku+dgp.r.št.6+pril.A1",
        "Sklep z dne 23. 3. 2016 (1)", "pi,si,", "sklep o ug. ",
        "Poziv z dne 29.3.2016, pr. sklep 7.5.2013",
        "sklep ustavitev premičnine   odredba seznam premoženja +sklep stroški 4.12.2015 s prilogo",
        "2x vloga 16.2.2016 (Ab) in vloga 16.2.2016"};
}
